Services: support in controller-sdk-go
teamhephy/controller-sdk-go pull request #2
Opened 2018-06-19 01:35 UTC by notmaxx

2018-09-12 18:40 UTC, Cryptophobia requested changes
See conversation here for package locations: https://github.com/teamhephy/workflow-cli/pull/33#issuecomment-420754720

2018-09-12 20:08 UTC, Cryptophobia requested changes

2018-09-12 20:08 UTC, Cryptophobia commented on services/services.go
> +// New adds a service to an app.
Can you provide a little more detail here for GoDocs? 

https://godoc.org/github.com/teamhephy/controller-sdk-go/apps#New

For example when creating a new app in the docs above, they talk about the newly created random name of the app. Here maybe write a bit more about procfileType and pathPattern that need to be passed to create new service object. Service is related to an application. You can't create a service without having an app first. It's obvious but I think good to be documented.

2018-09-12 20:08 UTC, Cryptophobia commented on services/services.go
> +// Delete service from app
Maybe write a bit more for the docs about the possible errors when trying to delete a service.

2018-09-13 02:38 UTC, notmaxx commented
@Cryptophobia done, btw, do you have autobuild for this?

2018-09-13 19:02 UTC, Cryptophobia commented on services/services.go
> +// Delete service from app
Very nice, now that is good documentation! :slightly_smiling_face:

2018-09-13 19:03 UTC, Cryptophobia approved these changes
:100:

2018-09-13 19:12 UTC, Cryptophobia commented
> @Cryptophobia done, btw, do you have autobuild for this?

We can integrate Travis CI builds for PR testing. Nice idea.

2018-09-13 20:02 UTC, Cryptophobia commented
@notmaxx , if you want to trigger travis build on branches now you need to merge latest from master so you get the .travis.yml file on your branch.

2018-09-13 22:05 UTC, notmaxx commented
@Cryptophobia done

2018-10-15 15:42 UTC, Cryptophobia approved these changes
LGTM

2018-10-15 15:42 UTC, merged

2018-10-15 15:43 UTC, Cryptophobia commented
Merged!